font_family family='JetBrainsMono Nerd Font' style=Regular
bold_font family='JetBrainsMono Nerd Font' style=Bold
italic_font auto
bold_italic_font auto
font_size 12.0
startup_session $HOME/.local/state/kitty/session.kitty-session

# Clipboard
map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard

# Window management
map ctrl+n new_os_window
map ctrl+w close_window

# Tab management
map ctrl+t new_tab
map ctrl+shift+] next_tab
map ctrl+shift+[ previous_tab
map ctrl+w close_tab

# Font sizes
map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0
